### PR TITLE
Refactor/CU-1nng6gq tailwind styles cmyk inscription

### PR DESCRIPTION
**Pull request by AndresRDC**
#{CU-1nng6gq}

# tailwind styles cmyk inscription
image
image
image
image

### CODE REVIEW

**Comment by SebasEC96** [comment]
@AndresRDC It looks great!!!! 🥳 One small detail, when you open the modal you can see the scrollbar although it is not necessary, this is because we are using the classname `"overflow-y-scroll"`, you can replace it with `"overflow-y-auto"`.
image

**Review by SebasEC96 — CHANGES_REQUESTED** [review]
@AndresRDC It looks great!!!! 🥳 One small detail, when you open the modal you can see the scrollbar although it is not necessary, this is because we are using the classname `"overflow-y-scroll"`, you can replace it with `"overflow-y-auto"`.
image

**Review by SebasEC96 — APPROVED** [review]
LGTM 😄

**Comment by hifrontendcafe** [comment]
Task linked: [CU-1nng6gq Reemplazar por tailwind src/pages/inscripcion-cmyk/styles.module.css](https://app.clickup.com/t/1nng6gq)

**Pull request closed without merging**
